version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output      
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  
  three:
    docker:
      - image: kshitijkabeer/continuous-integration-ros-ws:0.0.8
    steps:
      - run: ls -a
      - run: cd ../ && mkdir -p test_ws/src/$CIRCLE_PROJECT_REPONAME
      - checkout:
          path: /root/test_ws/src/$CIRCLE_PROJECT_REPONAME
      - run: ls ../test_ws/ -a
      - run: cd ../test_ws/ && wstool init src src/$CIRCLE_PROJECT_REPONAME/install_https.rosinstall && wstool update -t src
      - persist_to_workspace:
          root: /root
          paths:
            - test_ws/*
            
  four:
    docker:
      -image: kshitijkabeer/continuous-integration-ros-ws:0.0.8
    steps:
      - attach_workspace:
          at: /root
      - run: cd ../test_ws/ && source /opt/ros/melodic/setup.bash && catkin build
                  
workflows:
  version: 2
  one_and_two:
    jobs:
      - three
      - four:
          requires:
            - three